version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ipierette"
    assignees:
      - "ipierette"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major version updates for React
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore Three.js major updates
      - dependency-name: "three"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@react-three/fiber"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@react-three/drei"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ipierette"
    assignees:
      - "ipierette"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"

