# Workflow desativado para evitar duplicação de pipelines
name: CI/CD Pipeline

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-and-test:
    if: false
    runs-on: ubuntu-latest

    steps:
    - name: Workflow desativado
      run: echo "Este workflow foi desativado."
